
 export const SOCKET_CONNECT = "SOCKET_CONNECT";
 export const UPDATE_CALLEE = "UPDATE_CALLEE";
 export const UPDATE_CALLER = "UPDATE_CALLER";
 export const LOCAL_VIDEO_STREAM = "LOCAL_VIDEO_STREAM";
 export const REMOTE_VIDEO_STREAM = "REMOTE_VIDEO_STREAM";
 export const IS_NEGOTIATING = "IS_NEGOTIATING";